Add doc-update-roadmap.md
substrate-developer-hub/substrate-docs pull request #1116
Opened 2022-06-13 16:56 UTC by sacha-l

2022-06-14 14:36 UTC, lisa-parity reviewed
some suggestions

2022-06-14 15:33 UTC, NukeManDan commented
We should convert this to an issue and pin to this repo instead per talking with Lisa and Shawn

2022-06-14 15:34 UTC, NukeManDan requested changes
I can help get the issue templates updated, and update the new issue including the roadmap with links to them once ready

2022-06-15 13:11 UTC, NukeManDan commented on doc-update-roadmap.md
> +Bug report: :broken link: :code error: :content issue (wrong, unclear, out of date)
So you want to make a monolithic issue template? if so, is there an example of best practice for this I can emulate? I personally like the landing page we have with a couple options to help categorize and auto-tag for us. I don't think that is possible with just one issue for everything (would need to manually tag them all at least)

2022-06-16 15:20 UTC, NukeManDan commented
I will convert to issue and send a link to Jonny !

2022-06-16 16:50 UTC, NukeManDan commented
https://github.com/substrate-developer-hub/substrate-docs/issues/1131

2022-06-16 16:50 UTC, closed without merging