update meta title and desc
substrate-developer-hub/substrate-docs pull request #1199
Opened 2022-06-28 09:32 UTC by jonnysmillie

2022-06-28 10:16 UTC, rmnprkrl commented on config/siteMetadata.js
> +  description: `All of the Substrate tutorials and how-to guides require you to build and run a Substrate node in your development environment.`,
@jonnysmillie FYI
I'm checking on the text with marcomms, seems not well describing the project.

2022-06-29 15:25 UTC, rcos7 requested changes
Looks good, just a couple of comments

2022-06-29 15:25 UTC, rcos7 commented on src/components/site/NavLegal.js
> +          name="Element"
Looks like name is deprecated, can be replaced with an id if we need it
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2022-06-29 15:25 UTC, rcos7 commented on src/components/site/SEO.js
> +  const defaultTitle = title + ' | ' + siteMetadata.title || siteMetadata.title_meta;
nit: prefer template literals over concatenating strings

2022-06-30 09:44 UTC, rmnprkrl commented
@jonnysmillie LGTM

2022-06-30 09:58 UTC, merged