Lg/evm replacement
substrate-developer-hub/substrate-docs pull request #1240
Opened 2022-07-09 20:07 UTC by lisa-parity

Replacement for the old frontier workshop. While most of it "works" there are still some problems to be resolved.

2022-07-11 20:44 UTC, NukeManDan requested changes

2022-07-11 20:44 UTC, NukeManDan commented on content/config/nav.yaml
> +          url: /tutorials/connect-other-chains/access-evm-accounts/
how is this related to connection to other chains?

2022-07-11 20:50 UTC, lisa-parity commented
Enables interaction with EVM dapps/accounts. There are references to Moonbeam.
I'm not saying this is a perfect fit. I might add an integrations section later. But for the moment, I think this fits loosely into this category. Or I could remove it from the navigation altogether.

2022-07-12 13:29 UTC, NukeManDan commented
Frontier allows you to use EVM smart contracts. It also allows you to have the same cryptography for accounts, and an RPC that matches Ethereum so 3rd party apps can communicate with your node in the same way (interacting with EVM, via smart contracts)

 How is it _not_ a good fit for the contracts section? It has nothing at all to do with bridges, parachains, or any other cross consensus ideas. Just happens that Moonbeam uses this.

2022-07-13 08:45 UTC, shawntabrizi commented
I think bikeshedding the location of the content is not that important.

I do have a mental association with Frontier and EVM with the contracts world, but I think the whole tutorial section will probably need a revamp at some point anyway.

I think you should push it through if this is just the one outstanding problem.

2022-07-13 08:51 UTC, shawntabrizi commented
At some point, the best thing would be a plan for the tutorial section, including the tutorials that have already been created, and those which are not yet created, and the mental map of where all of them should be.

This could also be influenced by the "tutorial revamp" that I wanted @NukeManDan and @jonnysmillie to drive with the new kitties tutorial.

2022-07-13 08:52 UTC, NukeManDan approved these changes
OK, I trust Lisa's vision, even if I cannot quite grasp it yet 🙏

2022-07-13 21:31 UTC, lisa-parity commented
the structure will continue to evolve, but for now this update is primarily intended to fix a 404.

2022-07-13 21:31 UTC, merged