Add more warnings around the offchain worker example code
substrate-developer-hub/substrate-docs pull request #1852
Opened 2023-02-20 21:30 UTC by lisa-parity

2023-02-20 22:40 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +Although you must implement the `ValidateUnsigned` trait to send unsigned transactions, this check doesn't guarantee that a transaction was submitted by the offchain worker, that the transaction is a
```suggestion
Although you must implement the `ValidateUnsigned` trait to send unsigned transactions, this check doesn't guarantee that **only** offchain workers are able to send them. You should always consider the consequences of malicious actors sending these transactions as an attempt to tamper with the state of your chain.
```

2023-02-20 22:44 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +You should never assume that a transaction was submitted by an offchain worker.
```suggestion
You should never assume that the unsigned transaction can only be submitted by an offchain worker. The reality is that (by definition) **anyone** can submit them!
```

2023-02-20 22:45 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +You should always verify transactions—signed or unsigned—coming into the blockchain are from a legitimate source and haven't been tampered with.
I'd remove this line because it is impossible to verify the source of an unsigned transaction.
```suggestion
```

2023-02-20 22:55 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +	 This simple check wouldn't prevent an unauthorized actor from using the signed payload to modify state.
These lines are talking about Unsigned Tx w/ Signed Payloads but in the section of Unsigned Tx.

They should be moved to line `511`

2023-02-20 22:58 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +	 This simple check wouldn't prevent an unauthorized actor from using the signed payload to modify state.
```suggestion
	 However, you should note that the code in the example only checks whether the provided `signature` is valid for the `public` key contained inside `payload`. 
	 This check doesn't validate whether the signer is an offchain worker or authorized to call the specified function.
	 This simple check wouldn't prevent an unauthorized actor from using the signed payload to modify state.
```

2023-02-20 22:59 UTC, bernardoaraujor requested changes
suggesting some changes, overall looks good!

2023-02-22 23:17 UTC, lisa-parity commented
@bernardoaraujor thanks for your comments!
I might have gone a little off the rails trying to add some headings and clarifications so that I could follow the content a little more easily, so if you have time to take another look at the changes, that would be awesome. 
I'm thinking about "elevating" it to an actual tutorial (the how-to guides are generally a bit more sketchy about combining steps and not explaining the code)

2023-02-22 23:44 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +You should never assume that unsigned transactions are submitted by an offchain worker.
```suggestion
You should never assume that unsigned transactions could be submitted exclusively by an offchain worker. 
```

2023-02-22 23:45 UTC, bernardoaraujor commented on content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
> +	 However, you should note that the code in the example only checks whether the provided `signature` is valid for the  `public` key contained inside `payload`.
```suggestion
	 However, you should note that the code in the example only checks whether the provided `signature` is valid for the `public` key contained inside `payload`. 
```

2023-02-22 23:47 UTC, bernardoaraujor commented
suggested some small cosmetic changes, overall looks good to me!

2023-02-23 21:33 UTC, merged