Update examples and tutorials for deprecated index
substrate-developer-hub/substrate-docs pull request #2054
Opened 2023-09-05 10:48 UTC by Rashmirreddy

2023-09-05 10:49 UTC, Rashmirreddy commented
fixes "https://github.com/substrate-developer-hub/substrate-docs/issues/2035"

2023-09-06 11:44 UTC, juangirini requested changes
The changes on `content/md/en/docs/tutorials/build-application-logic/specify-the-origin-for-a-call.md` are incorrect. The other two files are ok

2023-09-07 07:56 UTC, juangirini approved these changes
LGTM

2023-09-07 11:45 UTC, wentelteefje approved these changes

2023-09-07 11:55 UTC, merged