Update macro to use by default for pallets
substrate-developer-hub/substrate-docs pull request #475
Opened 2021-11-03 09:56 UTC by NukeManDan

> Just FYI for all pallet developers and reviewers, all new pallets should have:
> 
> ```rust
> #[pallet::pallet]
> #[pallet::generate_store(pub(super) trait Store)]
> #[pallet::generate_storage_info]            <--- THIS LINE
> pub struct Pallet<T, I = ()>(PhantomData<(T, I)>);
> 
> Which will help ensure all of your storage items are bounded
> Old pallets do not have this, and we need to migrate them, but new pallets have no excuse :)
> We should consider flipping the behavior so that it is implicit it rather than needing to include it

From @shawntabrizi :point_up:
I will also update the template & example pallet in substrate & update the templates we own in this org, once this PR is apprved.

2021-11-03 09:56 UTC, NukeManDan commented on v3/docs/03-runtime/b-macros/index.mdx
Below is new content to review

2021-11-03 10:45 UTC, sacha-l commented
@NukeManDan : AFAIK the `pub struct Pallet<T, I = ()>(PhantomData<(T, I)>);` syntax is to handle pallet instantiability - not sure why we'd want that in all tutorials ? I think what's needed is just to add the `#[pallet::generate_storage_info]` line only.

2021-11-03 10:59 UTC, NukeManDan commented
Ah - makes sense to me. Should this instantiable syntax be highlighted somewhere in the docs I am not seeing? I can update to no PhantomData.

2021-11-03 17:30 UTC, sacha-l requested changes
I think instantiable pallets fall outside the scope of what this PR is trying to achieve, which is adding `#[pallet::generate_storage_info]`. On a separate note, would be nice to update [this guide](https://docs.substrate.io/how-to-guides/v3/basics/instantiable-pallets/) at some point!

2021-11-08 15:11 UTC, sacha-l approved these changes

2021-11-08 15:11 UTC, merged