fix pallet::Error KittyExists not found
substrate-developer-hub/substrate-docs pull request #897
Opened 2022-03-17 11:46 UTC by zhang-wenchao

fix no variant or associated item named `KittyExists` found for enum `pallet::Error` in the current scope

2022-03-17 14:56 UTC, NukeManDan approved these changes
lgtm cc @sacha-l may need to update the solution?

2022-03-24 17:26 UTC, sacha-l requested changes
Thanks for jumping in here, super appreciated. This change is fine for now, until we do a revamp of the tutorial to reflect the most up-to-date changes in the [solution code](https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/solutions/kitties). Minor suggestion to add more descriptive comments.

2022-03-24 17:26 UTC, sacha-l commented on v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
>  KittyNotExist,
```suggestion
/// This kitty already exists
KittyExists
/// This kitty doesn't exist
KittyNotExist,
```

2022-03-25 14:35 UTC, sacha-l approved these changes

2022-03-25 14:35 UTC, merged